# Generated by Django 5.1.4 on 2025-01-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_image_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecolor',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
